### ISSUE TITLE
cvte 模型训练程序

### ISSUE THREAD

**Issue by huangge1985** [naxingyu/kaldi_cvte_model_test#2]
Hello Mr Na

  有两个问题请教:
  1.cvte-v2模型的训练过程,可以提供源程序的么;
  2. 打算配置一台带GPU的电脑训练模型，能推荐一下么：
      在kaldi语音模型上，用3000h的数据，5天或一周完成训练，大概是什么样的配置和价位？

谢谢！！

Best regards

Best regards

**Comment by naxingyu** [comment]
cvte模型是CVTE公司用非公开数据训练的模型，没有公开训练过程。
